"""empty message

Revision ID: a1ef3aebea32
Revises: c2409c15a645
Create Date: 2020-04-05 16:28:42.984780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ef3aebea32'
down_revision = 'c2409c15a645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('photo_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'photo', 'photo_category', ['photo_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'photo_category_id')
    # ### end Alembic commands ###
